  - name: restart server
    shell: sleep 2 && shutdown -r now "Ansible triggered."
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting for the server up
    local_action: wait_for host={{YOUR TARGET HOST}} state=started delay=30 timeout=300
